# Generated by Django 4.2.5 on 2023-10-03 12:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9_]+$', 'Only alphabets, numbers, and underscores are allowed in the faculty name.')])),
                ('batch_year', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('1', 'SEM_1'), ('2', 'SEM_2'), ('3', 'SEM_3'), ('4', 'SEM_4'), ('5', 'SEM_5'), ('6', 'SEM_6'), ('7', 'SEM_7'), ('8', 'SEM_8')], default=1, max_length=1)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_semesters', to='api.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9_]+$', 'Only alphabets, numbers, and underscores are allowed in the subject name.')])),
                ('faculties', models.ManyToManyField(related_name='faculty_subjects', to='api.faculty')),
                ('semesters', models.ManyToManyField(related_name='semester_subjects', to='api.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z ]+$', 'Only alphabets and spaces are allowed in the teacher name.')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{1,3}[-.\\s]?\\d{1,14}$', 'Enter a valid phone number.')])),
                ('faculties', models.ManyToManyField(related_name='faculty_teachers', to='api.faculty')),
                ('semesters', models.ManyToManyField(related_name='semester_teachers', to='api.semester')),
                ('subjects', models.ManyToManyField(related_name='subject_teachers', to='api.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z ]+$', 'Only alphabets and spaces are allowed in the student name.')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('reg_no', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[\\w\\-]+$', 'Only alphanumeric characters, hyphens ("-"), and underscores ("_") are allowed in the registration number.')])),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_students', to='api.faculty')),
                ('semesters', models.ManyToManyField(related_name='semester_students', to='api.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(4.0)])),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_grade', to='api.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_grade', to='api.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_grade', to='api.subject')),
            ],
        ),
        migrations.AddConstraint(
            model_name='faculty',
            constraint=models.UniqueConstraint(fields=('faculty_name', 'batch_year'), name='unique_faculty_name_batch_year'),
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.UniqueConstraint(fields=('semester', 'faculty'), name='unique_semester_faculty'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('student', 'semester', 'subject'), name='unique_student_semester_subject'),
        ),
    ]
